language: node_js
node_js:
  - "node"
- "lts/*"
after_success:
  # requires azure env vars, as per readme
  - npm install
  - npm i -g serverless
  - serverless deploy --twitchApiKey ${twitchApiKey}